### PR TITLE
Fix bug: emails with attachments not showing correctly

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jeremy** [comment]
Could you explain?

**Comment by alphaone** [comment]
I have the same problem. If a mail has inline attachments (for images used in the mail) the mail_view will display the binary data of the images

**Comment by moll** [comment]
Just stumbled upon this problem myself, too. Seems like it's not merged to the latest mail_view 1.0.3 gem, either.

**Comment by ziazek** [comment]
Had the same problem. This fix works for me.

**Comment by jonleighton** [comment]
Also encountered this and the fix seems to work. I'll try to add a test for it tomorrow.

**Comment by jonleighton** [comment]
I think this problem is related to Action Mailer incorrectly generating the MIME layout - see rails/rails#2686.

This causes the `mail.parts` method to return e.g. an `image/png` part (for the attachment) and a `multipart/alternative` part containing the text and html parts. But neither of those two match `text/html`, so the `#find` returns nil, and we instead get `mail.parts.first` which is an `image/png`.

I think this will not be a problem when rails/rails#2686 is resolved, but in the mean time it would be good to have a workaround in mail_view to handle this.

**Comment by jonleighton** [comment]
Actually, ignore that. The problem is simply that Action Mailer uses a container multipart/alternative part, like this:

```
multipart/related
  multipart/alternative
    text/plain
    text/html
  attachment
```

Since the `mail.parts` method doesn't recurse, we only see the multipart/alternative and the attachment. Hence we need to use all_parts instead.

**Comment by jeremy** [comment]
Fixed by #28

**Pull request closed without merging**
