### PR TITLE
Added utf-8 charset into email.html.erb

### PR DESCRIPTION
**Pull request by sld**
Added utf-8 charset into email.html.erb because on Russian it will show uncorrect symbols on "Subject" for charset.

### CODE REVIEW

**Comment by jonduarte** [comment]
:+1: 

Nice! I was opening this project to propose that

**Comment by maxd** [comment]
:+1:  This pull request works fine.

**Comment by agirorn** [comment]
+1

**Comment by jeremy** [comment]
HTML5 should be assuming UTF-8. Why is the meta tag needed?

**Comment by maxd** [comment]
@jeremy Look at this [post](http://stackoverflow.com/questions/12406066/does-html5-specify-a-default-character-encoding-for-html-documents-if-no-charact) and related links. Looks like HTML5 doesn't specify default encoding in UTF-8.

**Comment by jeremy** [comment]
It does resolve to default UTF-8 ultimately, but it will try to sniff the charset if it's unspecified.

Specifying UTF-8 makes sense, but let's do it in the `Content-Type` header we return, then.

**Comment by jeremy** [comment]
Closing, stale & no progress. Open to a PR that sets the response header.

**Pull request closed without merging**
