### PR TITLE
Use an iframe for displaying mail contents

### PR DESCRIPTION
**Pull request by joeljunstrom**
Be sure you do not interfere with the email rendering

We've had issues with some of our emails not displaying correctly (most often because the message header would overlap the email message)

This is a bit of a hackish solution adding another request to display the email within a iframe so might just be regarded as a point of discussion but sharing is caring so here goes.

### CODE REVIEW

**Comment by jeremy** [comment]
Interesting idea. Anyone else tried this?

**Comment by akshayrawat** [comment]
@joeljunstrom @jeremy - Ran into this exact same problem today. The pull request above fixes it, confirmed!

**Comment by akshayrawat** [comment]
@joeljunstrom @jeremy 

This shows a dialog box which has an iframe showing the mailview contents



This problem was actually [fixed on master](https://github.com/37signals/mail_view/commit/fb2bb6264e89aa7ff43f1683a3c187d561938e88) a couple of months ago, and has not been released as a gem yet. That fixes this problem, unless @joeljunstrom fixed more problems we can close this issue (and please release an updated gem).

Thanks.

**Comment by joeljunstrom** [comment]
I think the fix on master most probably solved most (all?) problems.
But since styling for email clients is iffy at best I want the security of knowing that doubled body tags etc. does not compromise the rendering.

**Comment by jonleighton** [comment]
+1 to this

**Comment by look** [comment]
I would like to see this because it would make it easier to upload the mail to an email testing service, like Litmus.

**Comment by jeremy** [comment]
Thanks @joeljunstrom! Merged #34.

**Pull request closed without merging**
